### PR TITLE
[RFR] Adds share buttons

### PR DESCRIPTION
**Pull request by mattberridge**
Adds share buttons to Petition page and styles. They do nothing at present.
Also adds a few smaller petition info texts

pjtqpf6y8a

### CODE REVIEW

**Comment by mattberridge** [comment]
Ping @artibella @eschaefer @Tom-Bonnike @sigmarstern 

Puts them on page without functionality.

**Comment by louisefrom** [comment]
looks great @mattberridge, but would we be able to offer what'sapp sharing on desktop? I know there's a desktop app

**Comment by mattberridge** [comment]
@louisefrom that will come later on :)

**Comment by louisefrom** [comment]
@mattberridge 👍

**Pull request merged**
